/**:
  ros__parameters:
    imu_topic: imu/data
    dvl_topic: dvl/twist
    depth_topic: depth
    output_odom_topic: pose_gt
    pose_topic: localized_pose
    path_topic: localized_path
    world_frame: world
    base_frame: base_link
    publish_tf: true
    update_rate: 30.0
    initial_x: 0.0
    initial_y: 0.0
    initial_z: -200.0
    initial_yaw: 0.0
    depth_alpha: 0.5
    yaw_alpha: 0.3
    velocity_alpha: 0.45
    max_dt: 0.2
    sensor_timeout: 0.5
    max_path_length: 500
